"""add message entity 

Revision ID: 0a64ec52c4b5
Revises: 7d30b253cbba
Create Date: 2025-11-11 18:35:21.477274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a64ec52c4b5'
down_revision: Union[str, None] = '7d30b253cbba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'chat_id')
    # ### end Alembic commands ###
