"""initial revision

Revision ID: 75d4d639548a
Revises: 5d0870fd2e44
Create Date: 2025-11-10 23:34:45.271641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d4d639548a'
down_revision: Union[str, None] = '5d0870fd2e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('chatName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'chatName')
    # ### end Alembic commands ###
