"""nitial revision

Revision ID: 98004d379eef
Revises: 
Create Date: 2025-10-28 21:17:16.658149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98004d379eef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_user')
    op.drop_table('chat_user_table')
    op.drop_table('chat')
    op.drop_table('userApp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userApp',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='userApp_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chat',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('chat_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='chat_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('chat_user_table',
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='chat_user_table_chat_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['userApp.id'], name='chat_user_table_user_id_fkey')
    )
    op.create_table('chat_user',
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name='chat_user_chat_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['userApp.id'], name='chat_user_user_id_fkey')
    )
    # ### end Alembic commands ###
