"""initial revision

Revision ID: b6338a156f34
Revises: 75d4d639548a
Create Date: 2025-11-11 18:21:13.244584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6338a156f34'
down_revision: Union[str, None] = '75d4d639548a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'chatName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('chat_users_user_id_fkey', 'chat_users', type_='foreignkey')
    op.drop_constraint('chat_users_chat_id_fkey', 'chat_users', type_='foreignkey')
    op.create_foreign_key(None, 'chat_users', 'user_app', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_users', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_users', type_='foreignkey')
    op.drop_constraint(None, 'chat_users', type_='foreignkey')
    op.create_foreign_key('chat_users_chat_id_fkey', 'chat_users', 'chat', ['chat_id'], ['id'])
    op.create_foreign_key('chat_users_user_id_fkey', 'chat_users', 'user_app', ['user_id'], ['id'])
    op.alter_column('chat', 'chatName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
